spring:
  autoconfigure:
  cache:
    type: redis

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

    redis:
      host: localhost
      port: 6379
      timeout: 6000ms

  datasource:
    url: jdbc:mysql://34.60.104.129:3306/test
    username: root
    password: keypass
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/calendar.events
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile_image

            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-authentication-method: client_secret_post
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정


jwt:
  issuer: JinyoungPark
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.recap.domain.university.entity

server:
  port: 8080
  address: 0.0.0.0