spring:
  datasource:
    url: jdbc:mysql://34.60.104.129:3306/test
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  issuer: JinyoungPark
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.recap.domain.university.entity

server:
  port: 8080
  address: 0.0.0.0