name: CI / CD

on:
  push:
    branches: [jinyoung]

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: goormthon
      IMAGE_TAG: ${{ github.sha }}
      REGION: asia-northeast3  # 원하는 GCP 리전
      SERVICE_NAME: goormthon-service # Cloud Run 서비스 이름

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Google Cloud SDK 인증
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker 인증 구성
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (Test 제외)
        run: ./gradlew build --exclude-task test

      - name: Verify JAR file
        run: ls -la build/libs/

      - name: Docker 이미지 빌드 및 푸시
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Cloud Run에 배포
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: goormthon
          image: us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/docker/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          region: us-central1
          allow-unauthenticated: true